import type { Case } from './supabase'

// Displayed when Supabase is not configured — mirrors the seed data
export const STATIC_CASES: Case[] = [
  {
    id: '1', slug: 'fair-v-hhm-2025',
    title: 'Fair v. Hudson Homes Management LLC',
    jurisdiction: 'Supreme Court, Orleans County', state: 'NY', county: 'Orleans',
    filing_type: 'Civil — Misrepresentation', filed_date: '2025-01-01', status: 'Active',
    parties: 'Shannon Fair v. Hudson Homes Management LLC, Lone Star Funds',
    summary: 'According to the complaint, the plaintiff alleges systematic misrepresentation in property management practices. The filing names Lone Star Funds directly as a co-defendant.',
    source_url: 'https://unicourt.com/case/ny-sue1-caseggdd44370b4707-3249944', source_name: 'UniCourt',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '2', slug: 'sec-hudson-advisors-2022',
    title: 'SEC v. Hudson Advisors L.P. — Release No. 2022-159',
    jurisdiction: 'SEC (Administrative)', state: 'DC', county: null,
    filing_type: 'Regulatory — Securities', filed_date: '2022-01-01', status: 'Resolved — $11.2M Penalty',
    parties: 'SEC v. Hudson Advisors L.P., Lone Star Global Acquisitions Ltd.',
    summary: 'The SEC announced that the respondents agreed to pay $11.2 million in civil penalties for failing to disclose that fund fees were used to cover the founder\'s personal income tax liability — totaling $54.6 million over 13 years across 14 funds.',
    source_url: 'https://www.sec.gov/newsroom/press-releases/2022-159', source_name: 'SEC.gov',
    badge: 'agency', published: true, created_at: '', updated_at: '',
  },
  {
    id: '3', slug: 'korea-exchange-bank-2011',
    title: 'Republic of Korea v. Lone Star Funds',
    jurisdiction: 'South Korea Supreme Court', state: 'KR', county: null,
    filing_type: 'Criminal — Stock Manipulation', filed_date: '2011-01-01', status: 'Convicted (Upheld 2011)',
    parties: 'Republic of Korea v. Lone Star Funds / Paul Yoo',
    summary: 'A South Korean court found Lone Star Funds and executive Paul Yoo guilty of stock price manipulation in the acquisition of Korea Exchange Bank. Paul Yoo was sentenced to 3 years imprisonment. The Supreme Court upheld the conviction in 2011.',
    source_url: 'https://en.wikipedia.org/wiki/Korea_Exchange_Bank', source_name: 'Wikipedia',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '4', slug: 'hhm-v-tenant-ohio-2024',
    title: 'HHM v. Tenant — Standing Dismissed (Ohio)',
    jurisdiction: 'County Court', state: 'OH', county: null,
    filing_type: 'Eviction', filed_date: '2024-01-01', status: 'Dismissed — Standing',
    parties: 'Hudson Homes Management LLC v. Tenant',
    summary: 'According to BPIA reporting, the court dismissed the eviction after HHM failed to demonstrate its agency relationship with U.S. Bank Trust, N.A. as Trustee for LSF9 Master Participation Trust.',
    source_url: 'https://bpinvestigativeagency.com/hudson-homes-management-llc-fails-to-defend-its-agency-with-u-s-bank-trust-n-a-as-trustee-for-lsf9-master-participation-trust/', source_name: 'BPIA',
    badge: 'news', published: true, created_at: '', updated_at: '',
  },
  {
    id: '5', slug: 'weiss-v-hhm-oregon-2019',
    title: 'Weiss et al v. Hudson Homes Management LLC',
    jurisdiction: 'U.S. District Court, D. Oregon', state: 'OR', county: null,
    filing_type: 'Class Action', filed_date: '2019-01-01', status: 'Filed',
    parties: 'Weiss et al v. Hudson Homes Management LLC',
    summary: 'The docket reflects a federal class action filing in the District of Oregon concerning HHM\'s property management practices.',
    source_url: 'https://dockets.justia.com/docket/oregon/ordce/6:2019cv01104/146670', source_name: 'Justia',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '6', slug: 'hhm-v-hayden-fl-2020',
    title: 'HHM v. Hayden — Palm Beach County',
    jurisdiction: 'Palm Beach County', state: 'FL', county: 'Palm Beach',
    filing_type: 'Eviction', filed_date: '2020-01-01', status: 'Dismissed',
    parties: 'Hudson Homes Management LLC v. Hayden',
    summary: 'Public records show the eviction case was dismissed. The filing was made on behalf of U.S. Bank Trust, N.A. as Trustee for LSF9 Master Participation Trust.',
    source_url: 'https://unicourt.com/case/fl-pal-hudson-homes-management-llc-obo-us-bank-na-as-trustee-for-lsf9-master-participation-trust-v-hayden-marsha-753071', source_name: 'UniCourt',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '7', slug: 'hhm-v-white-tx-2023',
    title: 'HHM v. Kyesha White — Tarrant County',
    jurisdiction: 'Tarrant County', state: 'TX', county: 'Tarrant',
    filing_type: 'Eviction', filed_date: '2023-01-01', status: 'Default Judgment — $10,122',
    parties: 'Hudson Homes Management LLC v. Kyesha White',
    summary: 'The docket reflects a $10,122 default judgment entered against the tenant.',
    source_url: 'https://unicourt.com/case/tx-tr-hudson-homes-management-llc-vs-kyesha-white-and-all-occupants-1364907', source_name: 'UniCourt',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '8', slug: 'hhm-v-downing-pa-2022',
    title: 'HHM v. Downing — LSF10 — Lackawanna County',
    jurisdiction: 'Lackawanna County CCP', state: 'PA', county: 'Lackawanna',
    filing_type: 'Eviction', filed_date: '2022-01-01', status: 'Filed',
    parties: 'HHM as attorney-in-fact for U.S. Bank Trust for LSF10 v. Downing',
    summary: 'The filing identifies HHM acting as attorney-in-fact for U.S. Bank Trust, N.A. as Trustee for LSF10 Master Participation Trust — a separate trust entity within the Lone Star network.',
    source_url: 'https://www.docketalarm.com/cases/Pennsylvania_State_Court_of_Common_Pleas_Lackawanna_County/', source_name: 'DocketAlarm',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '9', slug: 'delhi-grayken-2022',
    title: 'Delhi Police v. John Grayken — RattanIndia Finance',
    jurisdiction: 'Delhi Police', state: 'IN', county: null,
    filing_type: 'Criminal — Breach of Trust', filed_date: '2022-01-01', status: 'Charges Filed',
    parties: 'Delhi Police v. John Grayken',
    summary: 'Delhi police accused founder John Grayken of criminal breach of trust, cheating, and criminal conspiracy related to ownership of RattanIndia Finance.',
    source_url: 'https://en.wikipedia.org/wiki/John_Grayken', source_name: 'Wikipedia',
    badge: 'news', published: true, created_at: '', updated_at: '',
  },
]
