import type { Case } from './supabase'

// Displayed when Supabase is not configured — mirrors the seed data
export const STATIC_CASES: Case[] = [
  {
    id: '1', slug: 'fair-v-hhm-2025',
    title: 'Fair v. Hudson Homes Management LLC',
    jurisdiction: 'Supreme Court, Orleans County', state: 'NY', county: 'Orleans',
    filing_type: 'Civil — Misrepresentation', filed_date: '2025-01-01', status: 'Active',
    parties: 'Shannon Fair v. Hudson Homes Management LLC, Lone Star Funds',
    summary: 'According to the complaint, the plaintiff alleges systematic misrepresentation in property management practices. The filing names Lone Star Funds directly as a co-defendant.',
    source_url: 'https://unicourt.com/case/ny-sue1-caseggdd44370b4707-3249944', source_name: 'UniCourt',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '2', slug: 'sec-hudson-advisors-2022',
    title: 'SEC v. Hudson Advisors L.P. — Release No. 2022-159',
    jurisdiction: 'SEC (Administrative)', state: 'DC', county: null,
    filing_type: 'Regulatory — Securities', filed_date: '2022-01-01', status: 'Resolved — $11.2M Penalty',
    parties: 'SEC v. Hudson Advisors L.P., Lone Star Global Acquisitions Ltd.',
    summary: 'The SEC announced that the respondents agreed to pay $11.2 million in civil penalties for failing to disclose that fund fees were used to cover the founder\'s personal income tax liability — totaling $54.6 million over 13 years across 14 funds.',
    source_url: 'https://www.sec.gov/newsroom/press-releases/2022-159', source_name: 'SEC.gov',
    badge: 'agency', published: true, created_at: '', updated_at: '',
  },
  {
    id: '3', slug: 'korea-exchange-bank-2011',
    title: 'Republic of Korea v. Lone Star Funds — Stock Manipulation',
    jurisdiction: 'South Korea Supreme Court', state: 'KR', county: null,
    filing_type: 'Criminal — Stock Manipulation', filed_date: '2011-01-01', status: 'Convicted (Upheld 2011)',
    parties: 'Republic of Korea v. Lone Star Funds / Paul Yoo',
    summary: 'A South Korean court found Lone Star Funds and executive Paul Yoo guilty of stock price manipulation in the acquisition of Korea Exchange Bank. Paul Yoo was sentenced to 3 years imprisonment. The Supreme Court upheld the conviction in 2011.',
    source_url: 'https://en.wikipedia.org/wiki/Korea_Exchange_Bank', source_name: 'Wikipedia',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '4', slug: 'hhm-v-tenant-ohio-2024',
    title: 'HHM v. Tenant — Standing Dismissed (Ohio, Nov. 2024)',
    jurisdiction: 'County Court, Ohio', state: 'OH', county: null,
    filing_type: 'Eviction', filed_date: '2024-11-01', status: 'Dismissed — Standing',
    parties: 'Hudson Homes Management LLC v. Tenant',
    summary: 'According to BPIA reporting, HHM filed an eviction claiming to be both the owner of the property and the agent for the lessor — LSF9 Master Participation Trust. The Magistrate granted leave for HHM to file a responsive brief proving its authority and standing. HHM failed to file any responsive brief and produced no evidence of standing at the hearing. The case was dismissed.',
    source_url: 'https://bpinvestigativeagency.com/hudson-homes-management-llc-fails-to-defend-its-agency-with-u-s-bank-trust-n-a-as-trustee-for-lsf9-master-participation-trust/', source_name: 'BP Investigative Agency',
    badge: 'news', published: true, created_at: '', updated_at: '',
  },
  {
    id: '5', slug: 'weiss-v-hhm-oregon-2019',
    title: 'Weiss et al v. Hudson Homes Management LLC',
    jurisdiction: 'U.S. District Court, D. Oregon', state: 'OR', county: null,
    filing_type: 'Class Action', filed_date: '2019-01-01', status: 'Filed',
    parties: 'Weiss et al v. Hudson Homes Management LLC',
    summary: 'The docket reflects a federal class action filing in the District of Oregon concerning HHM\'s property management practices.',
    source_url: 'https://dockets.justia.com/docket/oregon/ordce/6:2019cv01104/146670', source_name: 'Justia',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '6', slug: 'hhm-v-hayden-fl-2020',
    title: 'HHM v. Hayden — Palm Beach County',
    jurisdiction: 'Palm Beach County', state: 'FL', county: 'Palm Beach',
    filing_type: 'Eviction', filed_date: '2020-01-01', status: 'Dismissed',
    parties: 'Hudson Homes Management LLC v. Hayden',
    summary: 'Public records show the eviction case was dismissed. The filing was made on behalf of U.S. Bank Trust, N.A. as Trustee for LSF9 Master Participation Trust.',
    source_url: 'https://unicourt.com/case/fl-pal-hudson-homes-management-llc-obo-us-bank-na-as-trustee-for-lsf9-master-participation-trust-v-hayden-marsha-753071', source_name: 'UniCourt',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '7', slug: 'hhm-v-white-tx-2023',
    title: 'HHM v. Kyesha White — Tarrant County',
    jurisdiction: 'Tarrant County', state: 'TX', county: 'Tarrant',
    filing_type: 'Eviction', filed_date: '2023-01-01', status: 'Default Judgment — $10,122',
    parties: 'Hudson Homes Management LLC v. Kyesha White',
    summary: 'The docket reflects a $10,122 default judgment entered against the tenant.',
    source_url: 'https://unicourt.com/case/tx-tr-hudson-homes-management-llc-vs-kyesha-white-and-all-occupants-1364907', source_name: 'UniCourt',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '8', slug: 'hhm-v-downing-pa-2022',
    title: 'HHM v. Downing — LSF10 — Lackawanna County',
    jurisdiction: 'Lackawanna County CCP', state: 'PA', county: 'Lackawanna',
    filing_type: 'Eviction', filed_date: '2022-01-01', status: 'Filed',
    parties: 'HHM as attorney-in-fact for U.S. Bank Trust for LSF10 v. Downing',
    summary: 'The filing identifies HHM acting as attorney-in-fact for U.S. Bank Trust, N.A. as Trustee for LSF10 Master Participation Trust — a separate trust entity within the Lone Star network.',
    source_url: 'https://www.docketalarm.com/cases/Pennsylvania_State_Court_of_Common_Pleas_Lackawanna_County/', source_name: 'DocketAlarm',
    badge: 'public_record', published: true, created_at: '', updated_at: '',
  },
  {
    id: '9', slug: 'delhi-grayken-2022',
    title: 'Delhi Police v. John Grayken — RattanIndia Finance',
    jurisdiction: 'Delhi Police', state: 'IN', county: null,
    filing_type: 'Criminal — Breach of Trust', filed_date: '2022-01-01', status: 'Charges Filed',
    parties: 'Delhi Police v. John Grayken',
    summary: 'Delhi police accused founder John Grayken of criminal breach of trust, cheating, and criminal conspiracy. It is alleged that Grayken personally became the beneficial owner of RattanIndia Finance when he had told other shareholders that Lone Star Funds would do so.',
    source_url: 'https://en.wikipedia.org/wiki/John_Grayken', source_name: 'Wikipedia',
    badge: 'news', published: true, created_at: '', updated_at: '',
  },
  // ── NEW CASES (May 2026 update) ───────────────────────────────────────────
  {
    id: '10', slug: 'lone-star-v-korea-icsid-annulment-2025',
    title: 'Lone Star Funds v. Republic of Korea — ICSID Award Annulled',
    jurisdiction: 'ICSID (International Centre for Settlement of Investment Disputes)', state: 'INT', county: null,
    filing_type: 'Regulatory — International Arbitration', filed_date: '2025-11-18', status: 'Award Annulled — Nov. 18, 2025',
    parties: 'Lone Star Funds / LSF-KEB Holdings SCA v. Republic of Korea (ICSID Case No. ARB/12/37)',
    summary: 'On November 18, 2025, an ICSID ad hoc committee fully annulled a 2022 award that had ordered South Korea to pay Lone Star Funds approximately $230 million in damages. The committee found a serious departure from a fundamental rule of procedure — the original tribunal had relied heavily on an ICC arbitration award between Lone Star and Hana Financial as key evidence, but because South Korea was not a party to that arbitration and had no opportunity to contest its findings, this reliance violated due process. This was only the eighth full annulment in ICSID history, where annulment rates remain below 2%. The tribunal also ordered Lone Star to reimburse South Korea approximately $5 million in legal costs. Lone Star has signaled it will pursue a new arbitration, calling the annulment procedural. The case originated from Lone Star\'s 2003 acquisition of a controlling stake in Korea Exchange Bank (KEB) and its subsequent disputed sale.',
    source_url: 'https://www.kedglobal.com/legal-disputes/newsView/ked202511180007', source_name: 'KED Global / Arnold & Porter',
    badge: 'news', published: true, created_at: '2026-05-12', updated_at: '2026-05-12',
  },
  {
    id: '11', slug: 'zangara-v-lsf9-nm-supreme-court-2024',
    title: 'Zangara v. LSF9 Master Participation Trust — New Mexico Supreme Court',
    jurisdiction: 'New Mexico Supreme Court', state: 'NM', county: null,
    filing_type: 'Civil — Foreclosure / Standing', filed_date: '2024-01-01', status: 'Decided (2024)',
    parties: 'Kenneth & Kathy Zangara v. LSF9 Master Participation Trust',
    summary: 'The New Mexico Supreme Court addressed a case in which LSF9 Master Participation Trust\'s foreclosure action was dismissed for lack of standing. LSF9 had filed a foreclosure action in 2018 which was dismissed for lack of standing. The Trust then filed a second foreclosure action invoking New Mexico\'s six-month savings statute. The Supreme Court ultimately ruled on whether a prior dismissal for lack of standing constituted "negligence in prosecution," clarifying the meaning of New Mexico\'s savings statute in the context of LSF9\'s repeated standing failures. The underlying facts involved a $2.3 million loan secured by a mortgage originally held by Bank of America, later sold to LSF9.',
    source_url: 'https://law.justia.com/cases/new-mexico/supreme-court/2024/s-1-sc-39679-0.html', source_name: 'Justia',
    badge: 'public_record', published: true, created_at: '2026-05-12', updated_at: '2026-05-12',
  },
  {
    id: '12', slug: 'hhm-v-bryant-georgia-2025',
    title: 'HHM v. Bryant — Dispossessory Filing (Georgia, Aug. 2025)',
    jurisdiction: 'Georgia State Court', state: 'GA', county: null,
    filing_type: 'Eviction — Dispossessory', filed_date: '2025-08-27', status: 'Filed',
    parties: 'Hudson Homes Management LLC v. Bryant',
    summary: 'Public court records reflect a dispossessory (eviction) filing by Hudson Homes Management LLC in Georgia, presided over by Judge Kristina Hammer Blum, as of August 27, 2025.',
    source_url: 'https://trellis.law/case/13135/24-m-07389/hudson-homes-management-vs-bryant', source_name: 'Trellis.law',
    badge: 'public_record', published: true, created_at: '2026-05-12', updated_at: '2026-05-12',
  },
]
