[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/wp-admin/*"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/wordpress/*"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/wp-login.php"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/xmlrpc.php"
  to = "/404"
  status = 404
  force = true
